/*
 * Easypay API
 *
 * EasyPay - API
 *
 * The version of the OpenAPI document: 2.0.2
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Easypay.Rest.Client.Client;
using Easypay.Rest.Client.Model;

namespace Easypay.Rest.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface INotificationApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Authorisation notifications will be sent with this json
        /// </summary>
        /// <remarks>
        /// Authorisation Notification
        /// </remarks>
        /// <exception cref="Easypay.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorisationNotificationRequest">We will send you this json in our notification</param>
        /// <returns>StatusDetails</returns>
        StatusDetails AuthorisationNotification(AuthorisationNotificationRequest authorisationNotificationRequest);

        /// <summary>
        /// Authorisation notifications will be sent with this json
        /// </summary>
        /// <remarks>
        /// Authorisation Notification
        /// </remarks>
        /// <exception cref="Easypay.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorisationNotificationRequest">We will send you this json in our notification</param>
        /// <returns>ApiResponse of StatusDetails</returns>
        ApiResponse<StatusDetails> AuthorisationNotificationWithHttpInfo(AuthorisationNotificationRequest authorisationNotificationRequest);
        /// <summary>
        /// Generic notifications will be sent with this json
        /// </summary>
        /// <remarks>
        /// Generic Notification
        /// </remarks>
        /// <exception cref="Easypay.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="genericNotificationRequest">We will send you this json in our notifications</param>
        /// <returns>StatusDetails</returns>
        StatusDetails GenericNotification(GenericNotificationRequest genericNotificationRequest);

        /// <summary>
        /// Generic notifications will be sent with this json
        /// </summary>
        /// <remarks>
        /// Generic Notification
        /// </remarks>
        /// <exception cref="Easypay.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="genericNotificationRequest">We will send you this json in our notifications</param>
        /// <returns>ApiResponse of StatusDetails</returns>
        ApiResponse<StatusDetails> GenericNotificationWithHttpInfo(GenericNotificationRequest genericNotificationRequest);
        /// <summary>
        /// Transaction notification will be sent with this json
        /// </summary>
        /// <remarks>
        /// Transaction Notification
        /// </remarks>
        /// <exception cref="Easypay.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionNotificationRequest">We will send you this json in our notification</param>
        /// <returns>StatusDetails</returns>
        StatusDetails TransactionNotification(TransactionNotificationRequest transactionNotificationRequest);

        /// <summary>
        /// Transaction notification will be sent with this json
        /// </summary>
        /// <remarks>
        /// Transaction Notification
        /// </remarks>
        /// <exception cref="Easypay.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionNotificationRequest">We will send you this json in our notification</param>
        /// <returns>ApiResponse of StatusDetails</returns>
        ApiResponse<StatusDetails> TransactionNotificationWithHttpInfo(TransactionNotificationRequest transactionNotificationRequest);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface INotificationApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Authorisation notifications will be sent with this json
        /// </summary>
        /// <remarks>
        /// Authorisation Notification
        /// </remarks>
        /// <exception cref="Easypay.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorisationNotificationRequest">We will send you this json in our notification</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of StatusDetails</returns>
        System.Threading.Tasks.Task<StatusDetails> AuthorisationNotificationAsync(AuthorisationNotificationRequest authorisationNotificationRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Authorisation notifications will be sent with this json
        /// </summary>
        /// <remarks>
        /// Authorisation Notification
        /// </remarks>
        /// <exception cref="Easypay.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorisationNotificationRequest">We will send you this json in our notification</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (StatusDetails)</returns>
        System.Threading.Tasks.Task<ApiResponse<StatusDetails>> AuthorisationNotificationWithHttpInfoAsync(AuthorisationNotificationRequest authorisationNotificationRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Generic notifications will be sent with this json
        /// </summary>
        /// <remarks>
        /// Generic Notification
        /// </remarks>
        /// <exception cref="Easypay.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="genericNotificationRequest">We will send you this json in our notifications</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of StatusDetails</returns>
        System.Threading.Tasks.Task<StatusDetails> GenericNotificationAsync(GenericNotificationRequest genericNotificationRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Generic notifications will be sent with this json
        /// </summary>
        /// <remarks>
        /// Generic Notification
        /// </remarks>
        /// <exception cref="Easypay.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="genericNotificationRequest">We will send you this json in our notifications</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (StatusDetails)</returns>
        System.Threading.Tasks.Task<ApiResponse<StatusDetails>> GenericNotificationWithHttpInfoAsync(GenericNotificationRequest genericNotificationRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Transaction notification will be sent with this json
        /// </summary>
        /// <remarks>
        /// Transaction Notification
        /// </remarks>
        /// <exception cref="Easypay.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionNotificationRequest">We will send you this json in our notification</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of StatusDetails</returns>
        System.Threading.Tasks.Task<StatusDetails> TransactionNotificationAsync(TransactionNotificationRequest transactionNotificationRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Transaction notification will be sent with this json
        /// </summary>
        /// <remarks>
        /// Transaction Notification
        /// </remarks>
        /// <exception cref="Easypay.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionNotificationRequest">We will send you this json in our notification</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (StatusDetails)</returns>
        System.Threading.Tasks.Task<ApiResponse<StatusDetails>> TransactionNotificationWithHttpInfoAsync(TransactionNotificationRequest transactionNotificationRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface INotificationApi : INotificationApiSync, INotificationApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class NotificationApi : INotificationApi
    {
        private Easypay.Rest.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="NotificationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public NotificationApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotificationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public NotificationApi(String basePath)
        {
            this.Configuration = Easypay.Rest.Client.Client.Configuration.MergeConfigurations(
                Easypay.Rest.Client.Client.GlobalConfiguration.Instance,
                new Easypay.Rest.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Easypay.Rest.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Easypay.Rest.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Easypay.Rest.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotificationApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public NotificationApi(Easypay.Rest.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Easypay.Rest.Client.Client.Configuration.MergeConfigurations(
                Easypay.Rest.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Easypay.Rest.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Easypay.Rest.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Easypay.Rest.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NotificationApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public NotificationApi(Easypay.Rest.Client.Client.ISynchronousClient client, Easypay.Rest.Client.Client.IAsynchronousClient asyncClient, Easypay.Rest.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Easypay.Rest.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Easypay.Rest.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Easypay.Rest.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Easypay.Rest.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Easypay.Rest.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Authorisation notifications will be sent with this json Authorisation Notification
        /// </summary>
        /// <exception cref="Easypay.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorisationNotificationRequest">We will send you this json in our notification</param>
        /// <returns>StatusDetails</returns>
        public StatusDetails AuthorisationNotification(AuthorisationNotificationRequest authorisationNotificationRequest)
        {
            Easypay.Rest.Client.Client.ApiResponse<StatusDetails> localVarResponse = AuthorisationNotificationWithHttpInfo(authorisationNotificationRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Authorisation notifications will be sent with this json Authorisation Notification
        /// </summary>
        /// <exception cref="Easypay.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorisationNotificationRequest">We will send you this json in our notification</param>
        /// <returns>ApiResponse of StatusDetails</returns>
        public Easypay.Rest.Client.Client.ApiResponse<StatusDetails> AuthorisationNotificationWithHttpInfo(AuthorisationNotificationRequest authorisationNotificationRequest)
        {
            // verify the required parameter 'authorisationNotificationRequest' is set
            if (authorisationNotificationRequest == null)
                throw new Easypay.Rest.Client.Client.ApiException(400, "Missing required parameter 'authorisationNotificationRequest' when calling NotificationApi->AuthorisationNotification");

            Easypay.Rest.Client.Client.RequestOptions localVarRequestOptions = new Easypay.Rest.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Easypay.Rest.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Easypay.Rest.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = authorisationNotificationRequest;

            // authentication (accountId) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccountId")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccountId", this.Configuration.GetApiKeyWithPrefix("AccountId"));
            }
            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("ApiKey")))
            {
                localVarRequestOptions.HeaderParameters.Add("ApiKey", this.Configuration.GetApiKeyWithPrefix("ApiKey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<StatusDetails>("/your-authorisation-notification-endpoint", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AuthorisationNotification", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Authorisation notifications will be sent with this json Authorisation Notification
        /// </summary>
        /// <exception cref="Easypay.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorisationNotificationRequest">We will send you this json in our notification</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of StatusDetails</returns>
        public async System.Threading.Tasks.Task<StatusDetails> AuthorisationNotificationAsync(AuthorisationNotificationRequest authorisationNotificationRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Easypay.Rest.Client.Client.ApiResponse<StatusDetails> localVarResponse = await AuthorisationNotificationWithHttpInfoAsync(authorisationNotificationRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Authorisation notifications will be sent with this json Authorisation Notification
        /// </summary>
        /// <exception cref="Easypay.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorisationNotificationRequest">We will send you this json in our notification</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (StatusDetails)</returns>
        public async System.Threading.Tasks.Task<Easypay.Rest.Client.Client.ApiResponse<StatusDetails>> AuthorisationNotificationWithHttpInfoAsync(AuthorisationNotificationRequest authorisationNotificationRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'authorisationNotificationRequest' is set
            if (authorisationNotificationRequest == null)
                throw new Easypay.Rest.Client.Client.ApiException(400, "Missing required parameter 'authorisationNotificationRequest' when calling NotificationApi->AuthorisationNotification");


            Easypay.Rest.Client.Client.RequestOptions localVarRequestOptions = new Easypay.Rest.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = Easypay.Rest.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Easypay.Rest.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = authorisationNotificationRequest;

            // authentication (accountId) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccountId")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccountId", this.Configuration.GetApiKeyWithPrefix("AccountId"));
            }
            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("ApiKey")))
            {
                localVarRequestOptions.HeaderParameters.Add("ApiKey", this.Configuration.GetApiKeyWithPrefix("ApiKey"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<StatusDetails>("/your-authorisation-notification-endpoint", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AuthorisationNotification", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Generic notifications will be sent with this json Generic Notification
        /// </summary>
        /// <exception cref="Easypay.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="genericNotificationRequest">We will send you this json in our notifications</param>
        /// <returns>StatusDetails</returns>
        public StatusDetails GenericNotification(GenericNotificationRequest genericNotificationRequest)
        {
            Easypay.Rest.Client.Client.ApiResponse<StatusDetails> localVarResponse = GenericNotificationWithHttpInfo(genericNotificationRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Generic notifications will be sent with this json Generic Notification
        /// </summary>
        /// <exception cref="Easypay.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="genericNotificationRequest">We will send you this json in our notifications</param>
        /// <returns>ApiResponse of StatusDetails</returns>
        public Easypay.Rest.Client.Client.ApiResponse<StatusDetails> GenericNotificationWithHttpInfo(GenericNotificationRequest genericNotificationRequest)
        {
            // verify the required parameter 'genericNotificationRequest' is set
            if (genericNotificationRequest == null)
                throw new Easypay.Rest.Client.Client.ApiException(400, "Missing required parameter 'genericNotificationRequest' when calling NotificationApi->GenericNotification");

            Easypay.Rest.Client.Client.RequestOptions localVarRequestOptions = new Easypay.Rest.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Easypay.Rest.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Easypay.Rest.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = genericNotificationRequest;

            // authentication (accountId) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccountId")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccountId", this.Configuration.GetApiKeyWithPrefix("AccountId"));
            }
            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("ApiKey")))
            {
                localVarRequestOptions.HeaderParameters.Add("ApiKey", this.Configuration.GetApiKeyWithPrefix("ApiKey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<StatusDetails>("/your-generic-notification-endpoint", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GenericNotification", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Generic notifications will be sent with this json Generic Notification
        /// </summary>
        /// <exception cref="Easypay.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="genericNotificationRequest">We will send you this json in our notifications</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of StatusDetails</returns>
        public async System.Threading.Tasks.Task<StatusDetails> GenericNotificationAsync(GenericNotificationRequest genericNotificationRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Easypay.Rest.Client.Client.ApiResponse<StatusDetails> localVarResponse = await GenericNotificationWithHttpInfoAsync(genericNotificationRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Generic notifications will be sent with this json Generic Notification
        /// </summary>
        /// <exception cref="Easypay.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="genericNotificationRequest">We will send you this json in our notifications</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (StatusDetails)</returns>
        public async System.Threading.Tasks.Task<Easypay.Rest.Client.Client.ApiResponse<StatusDetails>> GenericNotificationWithHttpInfoAsync(GenericNotificationRequest genericNotificationRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'genericNotificationRequest' is set
            if (genericNotificationRequest == null)
                throw new Easypay.Rest.Client.Client.ApiException(400, "Missing required parameter 'genericNotificationRequest' when calling NotificationApi->GenericNotification");


            Easypay.Rest.Client.Client.RequestOptions localVarRequestOptions = new Easypay.Rest.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = Easypay.Rest.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Easypay.Rest.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = genericNotificationRequest;

            // authentication (accountId) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccountId")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccountId", this.Configuration.GetApiKeyWithPrefix("AccountId"));
            }
            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("ApiKey")))
            {
                localVarRequestOptions.HeaderParameters.Add("ApiKey", this.Configuration.GetApiKeyWithPrefix("ApiKey"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<StatusDetails>("/your-generic-notification-endpoint", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GenericNotification", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Transaction notification will be sent with this json Transaction Notification
        /// </summary>
        /// <exception cref="Easypay.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionNotificationRequest">We will send you this json in our notification</param>
        /// <returns>StatusDetails</returns>
        public StatusDetails TransactionNotification(TransactionNotificationRequest transactionNotificationRequest)
        {
            Easypay.Rest.Client.Client.ApiResponse<StatusDetails> localVarResponse = TransactionNotificationWithHttpInfo(transactionNotificationRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Transaction notification will be sent with this json Transaction Notification
        /// </summary>
        /// <exception cref="Easypay.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionNotificationRequest">We will send you this json in our notification</param>
        /// <returns>ApiResponse of StatusDetails</returns>
        public Easypay.Rest.Client.Client.ApiResponse<StatusDetails> TransactionNotificationWithHttpInfo(TransactionNotificationRequest transactionNotificationRequest)
        {
            // verify the required parameter 'transactionNotificationRequest' is set
            if (transactionNotificationRequest == null)
                throw new Easypay.Rest.Client.Client.ApiException(400, "Missing required parameter 'transactionNotificationRequest' when calling NotificationApi->TransactionNotification");

            Easypay.Rest.Client.Client.RequestOptions localVarRequestOptions = new Easypay.Rest.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Easypay.Rest.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Easypay.Rest.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = transactionNotificationRequest;

            // authentication (accountId) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccountId")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccountId", this.Configuration.GetApiKeyWithPrefix("AccountId"));
            }
            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("ApiKey")))
            {
                localVarRequestOptions.HeaderParameters.Add("ApiKey", this.Configuration.GetApiKeyWithPrefix("ApiKey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<StatusDetails>("/your-transaction-notification-endpoint", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("TransactionNotification", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Transaction notification will be sent with this json Transaction Notification
        /// </summary>
        /// <exception cref="Easypay.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionNotificationRequest">We will send you this json in our notification</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of StatusDetails</returns>
        public async System.Threading.Tasks.Task<StatusDetails> TransactionNotificationAsync(TransactionNotificationRequest transactionNotificationRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Easypay.Rest.Client.Client.ApiResponse<StatusDetails> localVarResponse = await TransactionNotificationWithHttpInfoAsync(transactionNotificationRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Transaction notification will be sent with this json Transaction Notification
        /// </summary>
        /// <exception cref="Easypay.Rest.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="transactionNotificationRequest">We will send you this json in our notification</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (StatusDetails)</returns>
        public async System.Threading.Tasks.Task<Easypay.Rest.Client.Client.ApiResponse<StatusDetails>> TransactionNotificationWithHttpInfoAsync(TransactionNotificationRequest transactionNotificationRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'transactionNotificationRequest' is set
            if (transactionNotificationRequest == null)
                throw new Easypay.Rest.Client.Client.ApiException(400, "Missing required parameter 'transactionNotificationRequest' when calling NotificationApi->TransactionNotification");


            Easypay.Rest.Client.Client.RequestOptions localVarRequestOptions = new Easypay.Rest.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = Easypay.Rest.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Easypay.Rest.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = transactionNotificationRequest;

            // authentication (accountId) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccountId")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccountId", this.Configuration.GetApiKeyWithPrefix("AccountId"));
            }
            // authentication (apiKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("ApiKey")))
            {
                localVarRequestOptions.HeaderParameters.Add("ApiKey", this.Configuration.GetApiKeyWithPrefix("ApiKey"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<StatusDetails>("/your-transaction-notification-endpoint", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("TransactionNotification", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
