/*
 * Easypay Payments API
 *
 * <a href='https://www.easypay.pt/en/legal-terms-and-conditions/' class='item'>Terms conditions and legal terms</a><br><a href='https://www.easypay.pt/en/privacy-and-data-protection-policy/' class='item'>Privacy Policy</a>
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Easypay.Rest.Client.Client;
using Easypay.Rest.Client.Api;
// uncomment below to import models
//using Easypay.Rest.Client.Model;

namespace Easypay.Rest.Client.Test.Api
{
    /// <summary>
    ///  Class for testing NotificationsWebhooksApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class NotificationsWebhooksApiTests : IDisposable
    {
        private NotificationsWebhooksApi instance;

        public NotificationsWebhooksApiTests()
        {
            instance = new NotificationsWebhooksApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NotificationsWebhooksApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' NotificationsWebhooksApi
            //Assert.IsType<NotificationsWebhooksApi>(instance);
        }

        /// <summary>
        /// Test YourAuthorisationNotificationEndpointPost
        /// </summary>
        [Fact]
        public void YourAuthorisationNotificationEndpointPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NotificationAuthorisation body = null;
            //instance.YourAuthorisationNotificationEndpointPost(body);
        }

        /// <summary>
        /// Test YourGenericNotificationEndpointPost
        /// </summary>
        [Fact]
        public void YourGenericNotificationEndpointPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NotificationGeneric notificationGeneric = null;
            //instance.YourGenericNotificationEndpointPost(notificationGeneric);
        }

        /// <summary>
        /// Test YourNotificationEndpointPost
        /// </summary>
        [Fact]
        public void YourNotificationEndpointPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NotificationCapture body = null;
            //instance.YourNotificationEndpointPost(body);
        }
    }
}
