/*
 * Easypay Payments API
 *
 * <a href='https://www.easypay.pt/en/legal-terms-and-conditions/' class='item'>Terms conditions and legal terms</a><br><a href='https://www.easypay.pt/en/privacy-and-data-protection-policy/' class='item'>Privacy Policy</a>
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Easypay.Rest.Client.Client;
using Easypay.Rest.Client.Api;
// uncomment below to import models
//using Easypay.Rest.Client.Model;

namespace Easypay.Rest.Client.Test.Api
{
    /// <summary>
    ///  Class for testing OutPaymentApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class OutPaymentApiTests : IDisposable
    {
        private OutPaymentApi instance;

        public OutPaymentApiTests()
        {
            instance = new OutPaymentApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OutPaymentApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' OutPaymentApi
            //Assert.IsType<OutPaymentApi>(instance);
        }

        /// <summary>
        /// Test OutPaymentGet
        /// </summary>
        [Fact]
        public void OutPaymentGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //decimal? page = null;
            //decimal? recordsPerPage = null;
            //string? type = null;
            //string? method = null;
            //string? id = null;
            //string? key = null;
            //double? value = null;
            //var response = instance.OutPaymentGet(page, recordsPerPage, type, method, id, key, value);
            //Assert.IsType<OutPaymentGet200Response>(response);
        }

        /// <summary>
        /// Test OutPaymentIdDelete
        /// </summary>
        [Fact]
        public void OutPaymentIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //instance.OutPaymentIdDelete(id);
        }

        /// <summary>
        /// Test OutPaymentIdGet
        /// </summary>
        [Fact]
        public void OutPaymentIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.OutPaymentIdGet(id);
            //Assert.IsType<OutPaymentIdGet200Response>(response);
        }

        /// <summary>
        /// Test OutPaymentPost
        /// </summary>
        [Fact]
        public void OutPaymentPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OutPaymentPostRequest? outPaymentPostRequest = null;
            //var response = instance.OutPaymentPost(outPaymentPostRequest);
            //Assert.IsType<OutPaymentPost201Response>(response);
        }
    }
}
