/*
 * Easypay Payments API
 *
 * <a href='https://www.easypay.pt/en/legal-terms-and-conditions/' class='item'>Terms conditions and legal terms</a><br><a href='https://www.easypay.pt/en/privacy-and-data-protection-policy/' class='item'>Privacy Policy</a>
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Easypay.Rest.Client.Model;
using Easypay.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Easypay.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing AuthorisationIdGet200ResponseMethod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuthorisationIdGet200ResponseMethodTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuthorisationIdGet200ResponseMethod
        //private AuthorisationIdGet200ResponseMethod instance;

        public AuthorisationIdGet200ResponseMethodTests()
        {
            // TODO uncomment below to create an instance of AuthorisationIdGet200ResponseMethod
            //instance = new AuthorisationIdGet200ResponseMethod();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuthorisationIdGet200ResponseMethod
        /// </summary>
        [Fact]
        public void AuthorisationIdGet200ResponseMethodInstanceTest()
        {
            // TODO uncomment below to test "IsType" AuthorisationIdGet200ResponseMethod
            //Assert.IsType<AuthorisationIdGet200ResponseMethod>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'LastFour'
        /// </summary>
        [Fact]
        public void LastFourTest()
        {
            // TODO unit test for the property 'LastFour'
        }

        /// <summary>
        /// Test the property 'CardType'
        /// </summary>
        [Fact]
        public void CardTypeTest()
        {
            // TODO unit test for the property 'CardType'
        }

        /// <summary>
        /// Test the property 'ExpirationDate'
        /// </summary>
        [Fact]
        public void ExpirationDateTest()
        {
            // TODO unit test for the property 'ExpirationDate'
        }
    }
}
