/*
 * Easypay Payments API
 *
 * <a href='https://www.easypay.pt/en/legal-terms-and-conditions/' class='item'>Terms conditions and legal terms</a><br><a href='https://www.easypay.pt/en/privacy-and-data-protection-policy/' class='item'>Privacy Policy</a>
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Easypay.Rest.Client.Model;
using Easypay.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Easypay.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing CaptureSplit
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CaptureSplitTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CaptureSplit
        //private CaptureSplit instance;

        public CaptureSplitTests()
        {
            // TODO uncomment below to create an instance of CaptureSplit
            //instance = new CaptureSplit();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CaptureSplit
        /// </summary>
        [Fact]
        public void CaptureSplitInstanceTest()
        {
            // TODO uncomment below to test "IsType" CaptureSplit
            //Assert.IsType<CaptureSplit>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'SplitKey'
        /// </summary>
        [Fact]
        public void SplitKeyTest()
        {
            // TODO unit test for the property 'SplitKey'
        }

        /// <summary>
        /// Test the property 'SplitDescriptive'
        /// </summary>
        [Fact]
        public void SplitDescriptiveTest()
        {
            // TODO unit test for the property 'SplitDescriptive'
        }

        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Fact]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'ClearingDate'
        /// </summary>
        [Fact]
        public void ClearingDateTest()
        {
            // TODO unit test for the property 'ClearingDate'
        }

        /// <summary>
        /// Test the property 'ClearingPeriod'
        /// </summary>
        [Fact]
        public void ClearingPeriodTest()
        {
            // TODO unit test for the property 'ClearingPeriod'
        }

        /// <summary>
        /// Test the property 'MarginAccount'
        /// </summary>
        [Fact]
        public void MarginAccountTest()
        {
            // TODO unit test for the property 'MarginAccount'
        }

        /// <summary>
        /// Test the property 'MarginValue'
        /// </summary>
        [Fact]
        public void MarginValueTest()
        {
            // TODO unit test for the property 'MarginValue'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Reverts'
        /// </summary>
        [Fact]
        public void RevertsTest()
        {
            // TODO unit test for the property 'Reverts'
        }
    }
}
