/*
 * Easypay Payments API
 *
 * <a href='https://www.easypay.pt/en/legal-terms-and-conditions/' class='item'>Terms conditions and legal terms</a><br><a href='https://www.easypay.pt/en/privacy-and-data-protection-policy/' class='item'>Privacy Policy</a>
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Easypay.Rest.Client.Model;
using Easypay.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Easypay.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing CaptureIdPost201Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CaptureIdPost201ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CaptureIdPost201Response
        //private CaptureIdPost201Response instance;

        public CaptureIdPost201ResponseTests()
        {
            // TODO uncomment below to create an instance of CaptureIdPost201Response
            //instance = new CaptureIdPost201Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CaptureIdPost201Response
        /// </summary>
        [Fact]
        public void CaptureIdPost201ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CaptureIdPost201Response
            //Assert.IsType<CaptureIdPost201Response>(instance);
        }

        /// <summary>
        /// Test the property 'PropertiesHasID'
        /// </summary>
        [Fact]
        public void PropertiesHasIDTest()
        {
            // TODO unit test for the property 'PropertiesHasID'
        }

        /// <summary>
        /// Test the property 'StatusDetails'
        /// </summary>
        [Fact]
        public void StatusDetailsTest()
        {
            // TODO unit test for the property 'StatusDetails'
        }
    }
}
