/*
 * Easypay Payments API
 *
 * <a href='https://www.easypay.pt/en/legal-terms-and-conditions/' class='item'>Terms conditions and legal terms</a><br><a href='https://www.easypay.pt/en/privacy-and-data-protection-policy/' class='item'>Privacy Policy</a>
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Easypay.Rest.Client.Model;
using Easypay.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Easypay.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing CheckoutPostRequestPaymentCapture
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CheckoutPostRequestPaymentCaptureTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CheckoutPostRequestPaymentCapture
        //private CheckoutPostRequestPaymentCapture instance;

        public CheckoutPostRequestPaymentCaptureTests()
        {
            // TODO uncomment below to create an instance of CheckoutPostRequestPaymentCapture
            //instance = new CheckoutPostRequestPaymentCapture();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CheckoutPostRequestPaymentCapture
        /// </summary>
        [Fact]
        public void CheckoutPostRequestPaymentCaptureInstanceTest()
        {
            // TODO uncomment below to test "IsType" CheckoutPostRequestPaymentCapture
            //Assert.IsType<CheckoutPostRequestPaymentCapture>(instance);
        }

        /// <summary>
        /// Test the property 'TransactionKey'
        /// </summary>
        [Fact]
        public void TransactionKeyTest()
        {
            // TODO unit test for the property 'TransactionKey'
        }

        /// <summary>
        /// Test the property 'CaptureDate'
        /// </summary>
        [Fact]
        public void CaptureDateTest()
        {
            // TODO unit test for the property 'CaptureDate'
        }

        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Fact]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }

        /// <summary>
        /// Test the property 'Splits'
        /// </summary>
        [Fact]
        public void SplitsTest()
        {
            // TODO unit test for the property 'Splits'
        }

        /// <summary>
        /// Test the property 'Descriptive'
        /// </summary>
        [Fact]
        public void DescriptiveTest()
        {
            // TODO unit test for the property 'Descriptive'
        }
    }
}
