/*
 * Easypay Payments API
 *
 * <a href='https://www.easypay.pt/en/legal-terms-and-conditions/' class='item'>Terms conditions and legal terms</a><br><a href='https://www.easypay.pt/en/privacy-and-data-protection-policy/' class='item'>Privacy Policy</a>
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Easypay.Rest.Client.Model;
using Easypay.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Easypay.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing CheckoutDetailsPayment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CheckoutDetailsPaymentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CheckoutDetailsPayment
        //private CheckoutDetailsPayment instance;

        public CheckoutDetailsPaymentTests()
        {
            // TODO uncomment below to create an instance of CheckoutDetailsPayment
            //instance = new CheckoutDetailsPayment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CheckoutDetailsPayment
        /// </summary>
        [Fact]
        public void CheckoutDetailsPaymentInstanceTest()
        {
            // TODO uncomment below to test "IsType" CheckoutDetailsPayment
            //Assert.IsType<CheckoutDetailsPayment>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Methods'
        /// </summary>
        [Fact]
        public void MethodsTest()
        {
            // TODO unit test for the property 'Methods'
        }

        /// <summary>
        /// Test the property 'ExpirationTime'
        /// </summary>
        [Fact]
        public void ExpirationTimeTest()
        {
            // TODO unit test for the property 'ExpirationTime'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'MaxValue'
        /// </summary>
        [Fact]
        public void MaxValueTest()
        {
            // TODO unit test for the property 'MaxValue'
        }

        /// <summary>
        /// Test the property 'MinValue'
        /// </summary>
        [Fact]
        public void MinValueTest()
        {
            // TODO unit test for the property 'MinValue'
        }

        /// <summary>
        /// Test the property 'Frequency'
        /// </summary>
        [Fact]
        public void FrequencyTest()
        {
            // TODO unit test for the property 'Frequency'
        }

        /// <summary>
        /// Test the property 'MaxCaptures'
        /// </summary>
        [Fact]
        public void MaxCapturesTest()
        {
            // TODO unit test for the property 'MaxCaptures'
        }

        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Fact]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }

        /// <summary>
        /// Test the property 'Failover'
        /// </summary>
        [Fact]
        public void FailoverTest()
        {
            // TODO unit test for the property 'Failover'
        }

        /// <summary>
        /// Test the property 'CaptureNow'
        /// </summary>
        [Fact]
        public void CaptureNowTest()
        {
            // TODO unit test for the property 'CaptureNow'
        }

        /// <summary>
        /// Test the property 'Retries'
        /// </summary>
        [Fact]
        public void RetriesTest()
        {
            // TODO unit test for the property 'Retries'
        }
    }
}
