/*
 * Easypay Payments API
 *
 * <a href='https://www.easypay.pt/en/legal-terms-and-conditions/' class='item'>Terms conditions and legal terms</a><br><a href='https://www.easypay.pt/en/privacy-and-data-protection-policy/' class='item'>Privacy Policy</a>
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Easypay.Rest.Client.Model;
using Easypay.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Easypay.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing FrequentAuthorisation201Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FrequentAuthorisation201ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FrequentAuthorisation201Response
        //private FrequentAuthorisation201Response instance;

        public FrequentAuthorisation201ResponseTests()
        {
            // TODO uncomment below to create an instance of FrequentAuthorisation201Response
            //instance = new FrequentAuthorisation201Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FrequentAuthorisation201Response
        /// </summary>
        [Fact]
        public void FrequentAuthorisation201ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" FrequentAuthorisation201Response
            //Assert.IsType<FrequentAuthorisation201Response>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
