/*
 * Easypay Payments API
 *
 * <a href='https://www.easypay.pt/en/legal-terms-and-conditions/' class='item'>Terms conditions and legal terms</a><br><a href='https://www.easypay.pt/en/privacy-and-data-protection-policy/' class='item'>Privacy Policy</a>
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Easypay.Rest.Client.Model;
using Easypay.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Easypay.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing InlineObject10Customer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject10CustomerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineObject10Customer
        //private InlineObject10Customer instance;

        public InlineObject10CustomerTests()
        {
            // TODO uncomment below to create an instance of InlineObject10Customer
            //instance = new InlineObject10Customer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineObject10Customer
        /// </summary>
        [Fact]
        public void InlineObject10CustomerInstanceTest()
        {
            // TODO uncomment below to test "IsType" InlineObject10Customer
            //Assert.IsType<InlineObject10Customer>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
    }
}
