/*
 * Easypay Payments API
 *
 * <a href='https://www.easypay.pt/en/legal-terms-and-conditions/' class='item'>Terms conditions and legal terms</a><br><a href='https://www.easypay.pt/en/privacy-and-data-protection-policy/' class='item'>Privacy Policy</a>
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Easypay.Rest.Client.Model;
using Easypay.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Easypay.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing OutPaymentPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OutPaymentPostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OutPaymentPostRequest
        //private OutPaymentPostRequest instance;

        public OutPaymentPostRequestTests()
        {
            // TODO uncomment below to create an instance of OutPaymentPostRequest
            //instance = new OutPaymentPostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OutPaymentPostRequest
        /// </summary>
        [Fact]
        public void OutPaymentPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OutPaymentPostRequest
            //Assert.IsType<OutPaymentPostRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Customer'
        /// </summary>
        [Fact]
        public void CustomerTest()
        {
            // TODO unit test for the property 'Customer'
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'ScheduleAt'
        /// </summary>
        [Fact]
        public void ScheduleAtTest()
        {
            // TODO unit test for the property 'ScheduleAt'
        }

        /// <summary>
        /// Test the property 'Descriptive'
        /// </summary>
        [Fact]
        public void DescriptiveTest()
        {
            // TODO unit test for the property 'Descriptive'
        }

        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Fact]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }

        /// <summary>
        /// Test the property 'OutAccount'
        /// </summary>
        [Fact]
        public void OutAccountTest()
        {
            // TODO unit test for the property 'OutAccount'
        }

        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }

        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
    }
}
