/*
 * Easypay Payments API
 *
 * <a href='https://www.easypay.pt/en/legal-terms-and-conditions/' class='item'>Terms conditions and legal terms</a><br><a href='https://www.easypay.pt/en/privacy-and-data-protection-policy/' class='item'>Privacy Policy</a>
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Easypay.Rest.Client.Model;
using Easypay.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Easypay.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PayByLinkCapture
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PayByLinkCaptureTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PayByLinkCapture
        //private PayByLinkCapture instance;

        public PayByLinkCaptureTests()
        {
            // TODO uncomment below to create an instance of PayByLinkCapture
            //instance = new PayByLinkCapture();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PayByLinkCapture
        /// </summary>
        [Fact]
        public void PayByLinkCaptureInstanceTest()
        {
            // TODO uncomment below to test "IsType" PayByLinkCapture
            //Assert.IsType<PayByLinkCapture>(instance);
        }

        /// <summary>
        /// Test the property 'Descriptive'
        /// </summary>
        [Fact]
        public void DescriptiveTest()
        {
            // TODO unit test for the property 'Descriptive'
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
    }
}
