/*
 * Easypay API
 *
 * EasyPay - API
 *
 * The version of the OpenAPI document: 2.0.2
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Easypay.Rest.Client.Api;
using Easypay.Rest.Client.Model;
using Easypay.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Easypay.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentSingleTransactionValues
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentSingleTransactionValuesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentSingleTransactionValues
        //private PaymentSingleTransactionValues instance;

        public PaymentSingleTransactionValuesTests()
        {
            // TODO uncomment below to create an instance of PaymentSingleTransactionValues
            //instance = new PaymentSingleTransactionValues();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentSingleTransactionValues
        /// </summary>
        [Fact]
        public void PaymentSingleTransactionValuesInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentSingleTransactionValues
            //Assert.IsType<PaymentSingleTransactionValues>(instance);
        }


        /// <summary>
        /// Test the property 'Requested'
        /// </summary>
        [Fact]
        public void RequestedTest()
        {
            // TODO unit test for the property 'Requested'
        }
        /// <summary>
        /// Test the property 'Paid'
        /// </summary>
        [Fact]
        public void PaidTest()
        {
            // TODO unit test for the property 'Paid'
        }
        /// <summary>
        /// Test the property 'FixedFee'
        /// </summary>
        [Fact]
        public void FixedFeeTest()
        {
            // TODO unit test for the property 'FixedFee'
        }
        /// <summary>
        /// Test the property 'VariableFee'
        /// </summary>
        [Fact]
        public void VariableFeeTest()
        {
            // TODO unit test for the property 'VariableFee'
        }
        /// <summary>
        /// Test the property 'Tax'
        /// </summary>
        [Fact]
        public void TaxTest()
        {
            // TODO unit test for the property 'Tax'
        }
        /// <summary>
        /// Test the property 'Transfer'
        /// </summary>
        [Fact]
        public void TransferTest()
        {
            // TODO unit test for the property 'Transfer'
        }

    }

}
