/*
 * Easypay Payments API
 *
 * <a href='https://www.easypay.pt/en/legal-terms-and-conditions/' class='item'>Terms conditions and legal terms</a><br><a href='https://www.easypay.pt/en/privacy-and-data-protection-policy/' class='item'>Privacy Policy</a>
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Easypay.Rest.Client.Model;
using Easypay.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Easypay.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentFrequentMethodResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentFrequentMethodResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentFrequentMethodResponse
        //private PaymentFrequentMethodResponse instance;

        public PaymentFrequentMethodResponseTests()
        {
            // TODO uncomment below to create an instance of PaymentFrequentMethodResponse
            //instance = new PaymentFrequentMethodResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentFrequentMethodResponse
        /// </summary>
        [Fact]
        public void PaymentFrequentMethodResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentFrequentMethodResponse
            //Assert.IsType<PaymentFrequentMethodResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }
    }
}
