/*
 * Easypay Payments API
 *
 * <a href='https://www.easypay.pt/en/legal-terms-and-conditions/' class='item'>Terms conditions and legal terms</a><br><a href='https://www.easypay.pt/en/privacy-and-data-protection-policy/' class='item'>Privacy Policy</a>
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Easypay.Rest.Client.Model;
using Easypay.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Easypay.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PostLinkRequestPayment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostLinkRequestPaymentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostLinkRequestPayment
        //private PostLinkRequestPayment instance;

        public PostLinkRequestPaymentTests()
        {
            // TODO uncomment below to create an instance of PostLinkRequestPayment
            //instance = new PostLinkRequestPayment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostLinkRequestPayment
        /// </summary>
        [Fact]
        public void PostLinkRequestPaymentInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostLinkRequestPayment
            //Assert.IsType<PostLinkRequestPayment>(instance);
        }

        /// <summary>
        /// Test the property 'Methods'
        /// </summary>
        [Fact]
        public void MethodsTest()
        {
            // TODO unit test for the property 'Methods'
        }

        /// <summary>
        /// Test the property 'Capture'
        /// </summary>
        [Fact]
        public void CaptureTest()
        {
            // TODO unit test for the property 'Capture'
        }

        /// <summary>
        /// Test the property 'Single'
        /// </summary>
        [Fact]
        public void SingleTest()
        {
            // TODO unit test for the property 'Single'
        }

        /// <summary>
        /// Test the property 'Frequent'
        /// </summary>
        [Fact]
        public void FrequentTest()
        {
            // TODO unit test for the property 'Frequent'
        }

        /// <summary>
        /// Test the property 'Subscription'
        /// </summary>
        [Fact]
        public void SubscriptionTest()
        {
            // TODO unit test for the property 'Subscription'
        }
    }
}
