/*
 * Easypay API
 *
 * EasyPay - API
 *
 * The version of the OpenAPI document: 2.0.2
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Easypay.Rest.Client.Api;
using Easypay.Rest.Client.Model;
using Easypay.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Easypay.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PropertiesHasListMetaData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PropertiesHasListMetaDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PropertiesHasListMetaData
        //private PropertiesHasListMetaData instance;

        public PropertiesHasListMetaDataTests()
        {
            // TODO uncomment below to create an instance of PropertiesHasListMetaData
            //instance = new PropertiesHasListMetaData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PropertiesHasListMetaData
        /// </summary>
        [Fact]
        public void PropertiesHasListMetaDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" PropertiesHasListMetaData
            //Assert.IsType<PropertiesHasListMetaData>(instance);
        }


        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Fact]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }

    }

}
