/*
 * Easypay Payments API
 *
 * <a href='https://www.easypay.pt/en/legal-terms-and-conditions/' class='item'>Terms conditions and legal terms</a><br><a href='https://www.easypay.pt/en/privacy-and-data-protection-policy/' class='item'>Privacy Policy</a>
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Easypay.Rest.Client.Model;
using Easypay.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Easypay.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PropertiesHasMinMaxValue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PropertiesHasMinMaxValueTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PropertiesHasMinMaxValue
        //private PropertiesHasMinMaxValue instance;

        public PropertiesHasMinMaxValueTests()
        {
            // TODO uncomment below to create an instance of PropertiesHasMinMaxValue
            //instance = new PropertiesHasMinMaxValue();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PropertiesHasMinMaxValue
        /// </summary>
        [Fact]
        public void PropertiesHasMinMaxValueInstanceTest()
        {
            // TODO uncomment below to test "IsType" PropertiesHasMinMaxValue
            //Assert.IsType<PropertiesHasMinMaxValue>(instance);
        }

        /// <summary>
        /// Test the property 'MaxValue'
        /// </summary>
        [Fact]
        public void MaxValueTest()
        {
            // TODO unit test for the property 'MaxValue'
        }

        /// <summary>
        /// Test the property 'MinValue'
        /// </summary>
        [Fact]
        public void MinValueTest()
        {
            // TODO unit test for the property 'MinValue'
        }

        /// <summary>
        /// Test the property 'UnlimitedPayments'
        /// </summary>
        [Fact]
        public void UnlimitedPaymentsTest()
        {
            // TODO unit test for the property 'UnlimitedPayments'
        }
    }
}
