/*
 * Easypay API
 *
 * EasyPay - API
 *
 * The version of the OpenAPI document: 2.0.2
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Easypay.Rest.Client.Api;
using Easypay.Rest.Client.Model;
using Easypay.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Easypay.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SinglePaymentUpdateRequestSddMandate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SinglePaymentUpdateRequestSddMandateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SinglePaymentUpdateRequestSddMandate
        //private SinglePaymentUpdateRequestSddMandate instance;

        public SinglePaymentUpdateRequestSddMandateTests()
        {
            // TODO uncomment below to create an instance of SinglePaymentUpdateRequestSddMandate
            //instance = new SinglePaymentUpdateRequestSddMandate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SinglePaymentUpdateRequestSddMandate
        /// </summary>
        [Fact]
        public void SinglePaymentUpdateRequestSddMandateInstanceTest()
        {
            // TODO uncomment below to test "IsType" SinglePaymentUpdateRequestSddMandate
            //Assert.IsType<SinglePaymentUpdateRequestSddMandate>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Iban'
        /// </summary>
        [Fact]
        public void IbanTest()
        {
            // TODO unit test for the property 'Iban'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'AccountHolder'
        /// </summary>
        [Fact]
        public void AccountHolderTest()
        {
            // TODO unit test for the property 'AccountHolder'
        }
        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Fact]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'MaxNumDebits'
        /// </summary>
        [Fact]
        public void MaxNumDebitsTest()
        {
            // TODO unit test for the property 'MaxNumDebits'
        }

    }

}
