/*
 * Easypay Payments API
 *
 * <a href='https://www.easypay.pt/en/legal-terms-and-conditions/' class='item'>Terms conditions and legal terms</a><br><a href='https://www.easypay.pt/en/privacy-and-data-protection-policy/' class='item'>Privacy Policy</a>
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Easypay.Rest.Client.Model;
using Easypay.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Easypay.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SubscriptionIdPatchRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubscriptionIdPatchRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubscriptionIdPatchRequest
        //private SubscriptionIdPatchRequest instance;

        public SubscriptionIdPatchRequestTests()
        {
            // TODO uncomment below to create an instance of SubscriptionIdPatchRequest
            //instance = new SubscriptionIdPatchRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubscriptionIdPatchRequest
        /// </summary>
        [Fact]
        public void SubscriptionIdPatchRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SubscriptionIdPatchRequest
            //Assert.IsType<SubscriptionIdPatchRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Capture'
        /// </summary>
        [Fact]
        public void CaptureTest()
        {
            // TODO unit test for the property 'Capture'
        }

        /// <summary>
        /// Test the property 'ExpirationTime'
        /// </summary>
        [Fact]
        public void ExpirationTimeTest()
        {
            // TODO unit test for the property 'ExpirationTime'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'Customer'
        /// </summary>
        [Fact]
        public void CustomerTest()
        {
            // TODO unit test for the property 'Customer'
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'Frequency'
        /// </summary>
        [Fact]
        public void FrequencyTest()
        {
            // TODO unit test for the property 'Frequency'
        }

        /// <summary>
        /// Test the property 'MaxCaptures'
        /// </summary>
        [Fact]
        public void MaxCapturesTest()
        {
            // TODO unit test for the property 'MaxCaptures'
        }

        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Fact]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }

        /// <summary>
        /// Test the property 'Failover'
        /// </summary>
        [Fact]
        public void FailoverTest()
        {
            // TODO unit test for the property 'Failover'
        }

        /// <summary>
        /// Test the property 'Retries'
        /// </summary>
        [Fact]
        public void RetriesTest()
        {
            // TODO unit test for the property 'Retries'
        }

        /// <summary>
        /// Test the property 'SddMandate'
        /// </summary>
        [Fact]
        public void SddMandateTest()
        {
            // TODO unit test for the property 'SddMandate'
        }
    }
}
