/*
 * Easypay Payments API
 *
 * <a href='https://www.easypay.pt/en/legal-terms-and-conditions/' class='item'>Terms conditions and legal terms</a><br><a href='https://www.easypay.pt/en/privacy-and-data-protection-policy/' class='item'>Privacy Policy</a>
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Easypay.Rest.Client.Model;
using Easypay.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Easypay.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SubscriptionIdPatchRequestCustomer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubscriptionIdPatchRequestCustomerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubscriptionIdPatchRequestCustomer
        //private SubscriptionIdPatchRequestCustomer instance;

        public SubscriptionIdPatchRequestCustomerTests()
        {
            // TODO uncomment below to create an instance of SubscriptionIdPatchRequestCustomer
            //instance = new SubscriptionIdPatchRequestCustomer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubscriptionIdPatchRequestCustomer
        /// </summary>
        [Fact]
        public void SubscriptionIdPatchRequestCustomerInstanceTest()
        {
            // TODO uncomment below to test "IsType" SubscriptionIdPatchRequestCustomer
            //Assert.IsType<SubscriptionIdPatchRequestCustomer>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

        /// <summary>
        /// Test the property 'PhoneIndicative'
        /// </summary>
        [Fact]
        public void PhoneIndicativeTest()
        {
            // TODO unit test for the property 'PhoneIndicative'
        }

        /// <summary>
        /// Test the property 'FiscalNumber'
        /// </summary>
        [Fact]
        public void FiscalNumberTest()
        {
            // TODO unit test for the property 'FiscalNumber'
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
    }
}
