/*
 * Easypay Payments API
 *
 * <a href='https://www.easypay.pt/en/legal-terms-and-conditions/' class='item'>Terms conditions and legal terms</a><br><a href='https://www.easypay.pt/en/privacy-and-data-protection-policy/' class='item'>Privacy Policy</a>
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Easypay.Rest.Client.Model;
using Easypay.Rest.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Easypay.Rest.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SubscriptionPost201ResponseMethod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubscriptionPost201ResponseMethodTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubscriptionPost201ResponseMethod
        //private SubscriptionPost201ResponseMethod instance;

        public SubscriptionPost201ResponseMethodTests()
        {
            // TODO uncomment below to create an instance of SubscriptionPost201ResponseMethod
            //instance = new SubscriptionPost201ResponseMethod();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubscriptionPost201ResponseMethod
        /// </summary>
        [Fact]
        public void SubscriptionPost201ResponseMethodInstanceTest()
        {
            // TODO uncomment below to test "IsType" SubscriptionPost201ResponseMethod
            //Assert.IsType<SubscriptionPost201ResponseMethod>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'SddMandate'
        /// </summary>
        [Fact]
        public void SddMandateTest()
        {
            // TODO unit test for the property 'SddMandate'
        }
    }
}
