/*
 * Easypay API
 *
 * EasyPay - API allows you to query payment meta-data, receive payment notifications and generate payment references. Two distinct environments - [Sandbox environment](https://api.test.easypay.pt/docs) and [Production environment](https://api.prod.easypay.pt/docs).
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BancoAlimentar.AlimentaEstaIdeia.easypay.Api;
using BancoAlimentar.AlimentaEstaIdeia.easypay.Model;
using BancoAlimentar.AlimentaEstaIdeia.easypay.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BancoAlimentar.AlimentaEstaIdeia.easypay.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentBase
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentBaseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentBase
        //private PaymentBase instance;

        public PaymentBaseTests()
        {
            // TODO uncomment below to create an instance of PaymentBase
            //instance = new PaymentBase();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentBase
        /// </summary>
        [Fact]
        public void PaymentBaseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentBase
            //Assert.IsType<PaymentBase>(instance);
        }


        /// <summary>
        /// Test the property 'ExpirationTime'
        /// </summary>
        [Fact]
        public void ExpirationTimeTest()
        {
            // TODO unit test for the property 'ExpirationTime'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'Customer'
        /// </summary>
        [Fact]
        public void CustomerTest()
        {
            // TODO unit test for the property 'Customer'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

    }

}
