/*
 * Easypay API
 *
 * EasyPay - API allows you to query payment meta-data, receive payment notifications and generate payment references. Two distinct environments - [Sandbox environment](https://api.test.easypay.pt/docs) and [Production environment](https://api.prod.easypay.pt/docs).
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BancoAlimentar.AlimentaEstaIdeia.easypay.Api;
using BancoAlimentar.AlimentaEstaIdeia.easypay.Model;
using BancoAlimentar.AlimentaEstaIdeia.easypay.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BancoAlimentar.AlimentaEstaIdeia.easypay.Test.Model
{
    /// <summary>
    ///  Class for testing PropertiesHasType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PropertiesHasTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PropertiesHasType
        //private PropertiesHasType instance;

        public PropertiesHasTypeTests()
        {
            // TODO uncomment below to create an instance of PropertiesHasType
            //instance = new PropertiesHasType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PropertiesHasType
        /// </summary>
        [Fact]
        public void PropertiesHasTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" PropertiesHasType
            //Assert.IsType<PropertiesHasType>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
