/*
 * Easypay API
 *
 * EasyPay - API allows you to query payment meta-data, receive payment notifications and generate payment references. Two distinct environments - [Sandbox environment](https://api.test.easypay.pt/docs) and [Production environment](https://api.prod.easypay.pt/docs).
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BancoAlimentar.AlimentaEstaIdeia.easypay.Api;
using BancoAlimentar.AlimentaEstaIdeia.easypay.Model;
using BancoAlimentar.AlimentaEstaIdeia.easypay.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BancoAlimentar.AlimentaEstaIdeia.easypay.Test.Model
{
    /// <summary>
    ///  Class for testing SddMandateDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SddMandateDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SddMandateDetails
        //private SddMandateDetails instance;

        public SddMandateDetailsTests()
        {
            // TODO uncomment below to create an instance of SddMandateDetails
            //instance = new SddMandateDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SddMandateDetails
        /// </summary>
        [Fact]
        public void SddMandateDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SddMandateDetails
            //Assert.IsType<SddMandateDetails>(instance);
        }


        /// <summary>
        /// Test the property 'Iban'
        /// </summary>
        [Fact]
        public void IbanTest()
        {
            // TODO unit test for the property 'Iban'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'AccountHolder'
        /// </summary>
        [Fact]
        public void AccountHolderTest()
        {
            // TODO unit test for the property 'AccountHolder'
        }
        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Fact]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'MaxNumDebits'
        /// </summary>
        [Fact]
        public void MaxNumDebitsTest()
        {
            // TODO unit test for the property 'MaxNumDebits'
        }

    }

}
