/*
 * Easypay API
 *
 * EasyPay - API allows you to query payment meta-data, receive payment notifications and generate payment references. Two distinct environments - [Sandbox environment](https://api.test.easypay.pt/docs) and [Production environment](https://api.prod.easypay.pt/docs).
 *
 * The version of the OpenAPI document: 2.0
 * Contact: tec@easypay.pt
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Easypay.Api;
using Easypay.Model;
using Easypay.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Easypay.Test.Model
{
    /// <summary>
    ///  Class for testing PropertiesHasPaymentStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PropertiesHasPaymentStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PropertiesHasPaymentStatus
        //private PropertiesHasPaymentStatus instance;

        public PropertiesHasPaymentStatusTests()
        {
            // TODO uncomment below to create an instance of PropertiesHasPaymentStatus
            //instance = new PropertiesHasPaymentStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PropertiesHasPaymentStatus
        /// </summary>
        [Fact]
        public void PropertiesHasPaymentStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" PropertiesHasPaymentStatus
            //Assert.IsType<PropertiesHasPaymentStatus>(instance);
        }


        /// <summary>
        /// Test the property 'PaymentStatus'
        /// </summary>
        [Fact]
        public void PaymentStatusTest()
        {
            // TODO unit test for the property 'PaymentStatus'
        }

    }

}
