name: EasyPay (.Net) CI

on:
  pull_request:
    branches: [ master ]

env: 
  CONFIGURATION: Release

jobs:
  build:
    name: Build SDK

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration ${{ env.CONFIGURATION }}
    - name: Test
      run: dotnet test --no-build --configuration ${{ env.CONFIGURATION }} --verbosity normal
