name: EasyPay (.Net) Generate

on:
  workflow_dispatch:
    inputs:
      spec:
        description: 'EasyPay OpenAPI Specification'
        required: true
        default: 'easypay-3.0.yaml'
      note:
        description: 'Spec Release Note'
        required: false
        default: 'Easypay spec pre-release'
  # push:
  #   branches: [ master ]
  #   tags:
  #     - 'v[0-9]+.[0-9]+.[0-9]+*'
  #   paths:
  #   - 'openapi-specs/*.yaml'
  #   - 'openapi-specs/*.yml'

env: 
  CONFIGURATION: Release
  OPENAPI_GENERATOR_SPEC: ./openapi-specs/${{ github.event.inputs.spec }}
  OPENAPI_GENERATOR_NAME: csharp-netcore
  OPENAPI_VERSION: '5.0.1'
  RELEASE_NOTE: 'easypay C# SDK Pre-release'
  GIT_USER_ID: banco-alimentar
  GIT_REPO_ID: easypay-client-csharp

jobs:
  build:
    name: Generate SDK

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install NBGV tool
      uses: dotnet/nbgv@master
      id: nbgv
      with:
        setAllVars: true
    - name: Install OpenApi-Generator
      run: |
        mkdir -p ${{ runner.temp }}/openapitools
        curl https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/bin/utils/openapi-generator-cli.sh > ${{ runner.temp }}/openapitools/openapi-generator-cli
        chmod u+x ${{ runner.temp }}/openapitools/openapi-generator-cli

    - name: Set OpenApi-Generator Version
      run: export OPENAPI_GENERATOR_VERSION=${{ env.OPENAPI_VERSION }}

    - name: Generate C# SDK with OpenApi-Generator
      run: ${{ runner.temp }}/openapitools/openapi-generator-cli generate --additional-properties=packageVersion=${{ steps.nbgv.outputs.Version }} -i ${{ env.OPENAPI_GENERATOR_SPEC }} -g ${{ env.OPENAPI_GENERATOR_NAME }} -c ./openapi-specs/config.dotnet.json --release-note "${{ env.RELEASE_NOTE }}" --git-user-id "${{ env.GIT_USER_ID }}" --git-repo-id "${{ env.GIT_REPO_ID }}"

    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: user.name "easypay-github-actions[bot]"
        author_email: "easypay-github-actions[bot]@noreply.easypay.pt"
        message: '${{ env.RELEASE_NOTE }}'
        add: '*'

    - name: Push SDK generated code
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        force: true



